config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # client Path
  get '/breed', to: 'home#breed', as: 'breed'
  post '/breed_fetch', to: 'home#fetch_breed', as: 'breed_fetch'

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # index page method
  def index; end

  # breed from method
  def breed; end

  # fetch breed
  def fetch_breed
    @dog_service = DogApiService.new(breed)
    @image_url   = @dog_service.fetch_image

    if @dog_service.success
      @message = "Successfully fetched image for #{breed.join(' ')}."
    else
      @message = "No image found for #{breed.join(' ')}."
    end

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def breed
    @breed ||= params[:breedInput].split(' ').uniq
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/breed.html.erb
<%= turbo_frame_tag id='breedForm' do %>
  <%= render 'shared/breed/form' %>
<% end %>

app/views/home/fetch_breed.turbo_stream.erb
<% if @dog_service.success %>
  <%= turbo_stream.update 'breed_info', partial: 'shared/breed/info', locals: { image_url: @image_url, breed: @breed.join(' ') } %>
  <%= turbo_stream.replace 'error_message', partial: 'shared/errors/message', locals: { error_message: '' } %>
<% else %>
  <%= turbo_stream.update 'error_message', partial: 'shared/errors/message', locals: { error_message: @message } %>
<% end %>

<%= turbo_stream.update 'breedForm', partial: 'shared/breed/form' %>

app/views/home/index.html.erb
<div class="container text-center">
  <div class="row">
    <div id='breedFormContainer' class='col container border border-white p-4 my-3'>
      <%= turbo_frame_tag id='breedForm', src: breed_path %>
    </div>
    <div id='breedInfoContainer'>
      <%= turbo_frame_tag id='breed_info' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogImageGenerator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/client/header' %>
    <%= turbo_frame_tag 'error_message' %>
    <%= yield %>
  </body>
</html>

app/views/shared/breed/_form.html.erb
<span data-controller='breed'>
  <%= form_tag(breed_fetch_path, method: :post) do %>
    <div class="mb-3">
      <%= label_tag "breedInput", "Breed", class: "form-label" %>
      <%= text_field_tag "breedInput", nil, class: "form-control", id: "breedInput", placeholder: 'Enter Dog Breed...' %>
    </div>
    <%= submit_tag "Submit", class: "btn btn-primary", data: { action: "click->breed#resetForm" }, id: 'breedSubmitButton', disabled: true %>
  <% end %>
</span>

app/views/shared/breed/_info.html.erb
<div class='container border border-white p-4 my-3'>
  <%= image_tag image_url, alt: 'Dog Breed Image', width: '350', height: '445' %>
  <p> <%= breed.titleize %></p>
</div>

app/views/shared/client/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Dog Image Generator</a>
  </div>
</nav>